api:
  base_url: "https://business-api.tiktok.com"
  region_endpoint: "/open_api/v1.3/search/region/"
  estimates_endpoint: "/open_api/v1.3/ad/audience_size/estimate/"
  max_workers: 3

paths:
  log_file: "logging/log.txt"
  input_csv: "data/raw/input.csv"
  input_json: "data/raw/input_json.json"
  location_ids: "data/raw/location_ids.csv"
  tt_output: "data/raw/tt_estimates.csv"
  tt_clean: "data/cleaned/tt_clean.csv"
  tt_final: "data/transformed/tt_final.csv"
  fb_csv: "data/raw/FB_mau_upper_202501_averaged.csv"
  fb_clean: "data/cleaned/fb_clean.csv"
  fb_final: "data/transformed/fb_final.csv"
  insta_csv: "data/raw/Ins_2025-01_averaged.csv"
  insta_clean: "data/cleaned/insta_clean.csv"
  insta_final: "data/transformed/insta_final.csv"
  pop_csv: "data/raw/un_1950_2023_processed.csv"
  pop_clean: "data/cleaned/pop_clean.csv"
  pop_final: "data/transformed/pop_final.csv"
